name: CrateyBackpack
description: $description
version: '${version}'

main: net.omni.crateyBackpack.CrateyBackpack
paperPluginLoader: net.omni.crateyBackpack.CrateyBackpackLoader
api-version: '1.21.11'
load: POSTWORLD

authors: [ domninos ]
